name: started
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo "On Runner instance"
      - name: Run a multi-line script
        run: |
            echo "Starting the task"
            rsync -zhrv ./* ec2-user@13.126.88.99:/home/ec2-user/actions-runner/work/started-github/started-github/yashu
