name: started
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: sh ./startedgithub.sh
      - name: Run a multi-line script
        run: |
            echo Nothing to see in multi line script
            echo what is in that folder?
            ls -a
            mkdir yashu
            touch file1.txt
